version: '3.8'
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - chroma
      - redis

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jarvis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    restart: always
    ports:
      - "8001:8000"   # Adjust port if necessary
    environment:
      - CHROMA_DB=/data
    volumes:
      - chroma_data:/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  chroma_data:
